<?php

namespace Blogger\BlogBundle\Entity\Repository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends \Doctrine\ORM\EntityRepository{
    public function getCompany(){
        $qb = $this->createQueryBuilder('c')
            ->select('c');
//            ->addOrderBy('c.id', 'DESC');
        return $qb->getQuery()->getResult();
    }

    public function getCompanyOnId($id){
        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.id = :c_id')
            ->setParameter('c_id', $id);
        return $qb->getQuery()->getResult();
    }

    public function deleteCompany($id){

        $qb = $this->createQueryBuilder('BloggerBlogBundle:Company', 'c')
            ->delete('BloggerBlogBundle:Company', 'c')
            ->where('c.id = :c_id')
            ->setParameter('c_id', $id);

        return $qb->getQuery()->getResult();
    }
}
