<?php

namespace Blogger\BlogBundle\Entity\Repository;

/**
 * GroupStudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupStudentRepository extends \Doctrine\ORM\EntityRepository{
    public function getGroup(){
        $qb = $this->createQueryBuilder('g')
            ->select('g');
//            ->addOrderBy('c.id', 'DESC');
        return $qb->getQuery()->getResult();
    }

    public function deleteGroup($id){

        $qb = $this->createQueryBuilder('BloggerBlogBundle:GroupStudent', 'g')
            ->delete('BloggerBlogBundle:GroupStudent', 'g')
            ->where('g.id = :g_id')
            ->setParameter('g_id', $id);

        return $qb->getQuery()->getResult();
    }
}
