<?php

namespace Blogger\BlogBundle\Entity\Repository;

/**
 * SliderPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SliderPageRepository extends \Doctrine\ORM\EntityRepository{
    public function getCompany(){
        $qb = $this->createQueryBuilder('s')
            ->select('s');
//            ->addOrderBy('c.id', 'DESC');
        return $qb->getQuery()->getResult();
    }

    public function deleteSlider($id){

        $qb = $this->createQueryBuilder('BloggerBlogBundle:SliderPage', 's')
            ->delete('BloggerBlogBundle:SliderPage', 's')
            ->where('s.id = :s_id')
            ->setParameter('s_id', $id);

        return $qb->getQuery()->getResult();
    }
}
